### ISSUE TITLE
[improvement] QR Code outline not at optimal position

### ISSUE THREAD

**Issue by Merith-TK** [Epicpkmn11/dsidl#3]
in my testing, the QR Code outline boarder is not in the optimal position for scanning an QR code when lined up perfectly, 

the outer corners of the QR code need to match the inner corners of the template, 

it it possible that maybe it is grabbing the overlay on the image as well?

**Comment by Epicpkmn11** [comment]
The overlay definitely isn't affecting the scanning, it uses a fresh 640×480 frame not anything from VRAM for the scan, I didn't do much testing for ideal size/position though and just went for 'almost full screen and centered'...

You're saying the scan area should be a bit smaller, right? Does this seem better:

![overlay](https://user-images.githubusercontent.com/41608708/174086945-01a46b31-cfc6-46c8-9b5d-c3e9f6edf4b3.png)

**Comment by Merith-TK** [comment]
the new outline is *perfect* and can get consistant detection
