### ISSUE TITLE
[improvement] Alter dsidl:src scheme to be an bit more verbose if possible

### ISSUE THREAD

**Issue by Merith-TK** [Epicpkmn11/dsidl#6]
the idea is that we should alter the scheme to allow preventing downloading already existing files, provided an hash is provided (something basic like an md5?)

proposed altered format
```json
{
	"dsidl": 1,
	"script": {
		"/program.nds": {
			"url": "https://github.com/Merith-TK/dsidl/releases/download/release-test/dsidl.dsi",
			"hash" : "2480be6feacb4c14564ca4922abfd852" // again, md5 hash
			"overwrite": false // if hash matches, dont overwrite
		},
		"/program.config": {
			"url": "https://example.com/program.config",
			"overwrite": false // in this case, if file matches, do not overwrite
		}
	}
}
```
if hash does not match, re-download the file, 
this can save time should someone use the dsidl:src format for multiple files,

**Comment by Epicpkmn11** [comment]
SHA1 would be the best hash as the DSi has a BIOS function for it, but even is very slow so not sure it would actually save any time... It'd probably be quicker to just say *no don't download* than to calculate the SHA1 of most files on DSi.

I think what would work better is just an arbitrary `"version"` (which could be a hash if wanted) and store that to a JSON somewhere or so, but imo that's still a bit out of scope.

**Comment by Merith-TK** [comment]
fair enough, just think at the very least the "overwrite" function should be implemented so someone can update an program that uses the `dsidl:src` method without having to reset all of their configs,

**Comment by Epicpkmn11** [comment]
How often do you actually download a config though? I guess SNEmulDS needs it, but most other things will generate that when you run it rather than being a download...

**Comment by Merith-TK** [comment]
say someone decides to make an lua interpetor for the DSi (i know microLua exists but thats DS mode, and cannot take advantage of DSi mode) 

they wouldnt want to have their user re-download all of the lua files if no update was made to them?

**Comment by Epicpkmn11** [comment]
Closed as partially completed, hash checks not implemented by I may look into either that or arbitrary version tracking in the future.
